wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1663630822
    t:
      1:
      - 1
      - 5
      - 6
      - 8
      - 53
      - 55
      4: 3.8.10
      5: 0.12.20
      8:
      - 5
